import { NextResponse } from "next/server";

export async function GET() {
  return NextResponse.json([
    {
      "resource_state": 2,
      "athlete": {
        "id": 14952541,
        "resource_state": 1
      },
      "name": "Afternoon Swim",
      "distance": 1000.0,
      "moving_time": 2055,
      "elapsed_time": 2055,
      "total_elevation_gain": 0,
      "type": "Swim",
      "sport_type": "Swim",
      "id": 9450331101,
      "start_date": "2023-07-14T15:08:32Z",
      "start_date_local": "2023-07-14T16:08:32Z",
      "timezone": "(GMT+00:00) Europe/London",
      "utc_offset": 3600.0,
      "location_city": null,
      "location_state": null,
      "location_country": "United Kingdom",
      "achievement_count": 0,
      "kudos_count": 1,
      "comment_count": 0,
      "athlete_count": 1,
      "photo_count": 0,
      "map": {
        "id": "a9450331101",
        "summary_polyline": "",
        "resource_state": 2
      },
      "trainer": false,
      "commute": false,
      "manual": true,
      "private": false,
      "visibility": "everyone",
      "flagged": false,
      "gear_id": null,
      "start_latlng": [],
      "end_latlng": [],
      "average_speed": 0.487,
      "max_speed": 0,
      "has_heartrate": false,
      "heartrate_opt_out": false,
      "display_hide_heartrate_option": false,
      "upload_id": null,
      "external_id": null,
      "from_accepted_tag": false,
      "pr_count": 0,
      "total_photo_count": 0,
      "has_kudoed": false
    },
    {
      "resource_state": 2,
      "athlete": {
        "id": 14952541,
        "resource_state": 1
      },
      "name": "Afternoon Ride",
      "distance": 22571.0,
      "moving_time": 2700,
      "elapsed_time": 2700,
      "total_elevation_gain": 0,
      "type": "VirtualRide",
      "sport_type": "VirtualRide",
      "id": 9444286073,
      "start_date": "2023-07-13T15:04:54Z",
      "start_date_local": "2023-07-13T16:04:54Z",
      "timezone": "(GMT+00:00) Europe/London",
      "utc_offset": 3600.0,
      "location_city": null,
      "location_state": null,
      "location_country": "United Kingdom",
      "achievement_count": 0,
      "kudos_count": 1,
      "comment_count": 0,
      "athlete_count": 1,
      "photo_count": 0,
      "map": {
        "id": "a9444286073",
        "summary_polyline": "",
        "resource_state": 2
      },
      "trainer": false,
      "commute": false,
      "manual": true,
      "private": false,
      "visibility": "everyone",
      "flagged": false,
      "gear_id": null,
      "start_latlng": [],
      "end_latlng": [],
      "average_speed": 8.36,
      "max_speed": 0,
      "has_heartrate": false,
      "heartrate_opt_out": false,
      "display_hide_heartrate_option": false,
      "upload_id": null,
      "external_id": null,
      "from_accepted_tag": false,
      "pr_count": 0,
      "total_photo_count": 0,
      "has_kudoed": false
    },
    {
      "resource_state": 2,
      "athlete": {
        "id": 14952541,
        "resource_state": 1
      },
      "name": "Evening Run",
      "distance": 5112.6,
      "moving_time": 1575,
      "elapsed_time": 1575,
      "total_elevation_gain": 36.0,
      "type": "Run",
      "sport_type": "Run",
      "workout_type": 0,
      "id": 9438488832,
      "start_date": "2023-07-12T16:46:09Z",
      "start_date_local": "2023-07-12T17:46:09Z",
      "timezone": "(GMT+00:00) Europe/London",
      "utc_offset": 3600.0,
      "location_city": null,
      "location_state": null,
      "location_country": "United Kingdom",
      "achievement_count": 0,
      "kudos_count": 4,
      "comment_count": 0,
      "athlete_count": 1,
      "photo_count": 0,
      "map": {
        "id": "a9438488832",
        "summary_polyline": "ajryH`sh@Lw@LYLm@FIT_ADE?IF_@JY?QBIDCDWDk@?g@@SVyAf@_AFOHOFEDMB[JWLqAT[DQHEVe@@I\\e@F?P^JFTTTn@X^@NDH^n@DN\\f@HPHFDAFID?BBPDNL`@n@BHD@NND?DCf@s@JGBMPMFOPQJ?DCHWHGR[\\[Zm@LGd@k@ZO@IJEDKHCDGHGDGNEHK`@]LCX[\\O?IDEx@i@HOROPUXMFKB?FCHMRQHCHILCLQPIFMPG`@[BO`@WLUHC\\WTEDERUXMROPUFCDKNKVEDEBMHM^_@VEFI\\CJCFGH?HMH\\TKBIAILGDIBDD?ZQXELGJALT?LFh@APH^Fv@?TJfA?^FRA\\NfADF@JEJ@XCHDTDDHV?JJh@Dr@BFBj@BD@NFTBj@DVJjAVbB?\\D`@JPAPDbAFVFf@DDDPB^H`@?LBDHb@Dv@BNAJ@XDDDRA\\HRFn@PfAh@fCBz@Ll@@TFb@?PF\\@VHl@FTB@?PDP@LDNAHFNFh@?PJj@?Jb@fEADG@UREAOPIEGBQPYNUXQHGHE?UTILGAEFGDGAKBSREAUXELO@KFO?QLGNKBEHEA]\\YHK?KBGRCDQFGPE?EDCHSBCDUFETEBM\\SAA@AEKJCNIHEJIJYPG?QJETGJQHGHI@KRSNOCUPG?[XCJUNk@r@WNOTEBELKHI@KNGLOLW^SPEJSRQVg@f@Yh@[PKJIPI@KVi@`@Uf@[TGNMTKF_@`@IFW`@[RMVY^IDILQP_@p@MDK?_@RG?]b@[NIHEAIHE?ED@BSDG?E@CAW@IDM@[F_AIK@SGg@AOKEAIBWU@EGGICGGG[?WGCIa@GICIIISq@@QEYEIMESa@Me@Ca@I[YiAUs@CU@ICMIGMMKg@MUWOMQUQc@OEG[GKO_@GQOM?IEc@Ca@IYMK?WKC?cAWM?GIS?SOi@ISMO@IAEWBM@k@Ag@BOAQDg@BIBeBD[Jc@B[AQD]Ck@Ni@HeA",
        "resource_state": 2
      },
      "trainer": false,
      "commute": false,
      "manual": false,
      "private": false,
      "visibility": "everyone",
      "flagged": false,
      "gear_id": "g13518149",
      "start_latlng": [
        51.54558124020696,
        -0.21500051021575928
      ],
      "end_latlng": [
        51.54549431987107,
        -0.2148247417062521
      ],
      "average_speed": 3.246,
      "max_speed": 5.706,
      "has_heartrate": false,
      "heartrate_opt_out": false,
      "display_hide_heartrate_option": false,
      "elev_high": 62.0,
      "elev_low": 33.6,
      "upload_id": 10123050385,
      "upload_id_str": "10123050385",
      "external_id": "5DCF56F4-A074-455F-A6E6-B1021A7F1B0B-activity.fit",
      "from_accepted_tag": false,
      "pr_count": 0,
      "total_photo_count": 0,
      "has_kudoed": false
    },
    {
      "resource_state": 2,
      "athlete": {
        "id": 14952541,
        "resource_state": 1
      },
      "name": "Afternoon Swim",
      "distance": 800.0,
      "moving_time": 1500,
      "elapsed_time": 1500,
      "total_elevation_gain": 0,
      "type": "Swim",
      "sport_type": "Swim",
      "id": 9438118261,
      "start_date": "2023-07-12T15:49:00Z",
      "start_date_local": "2023-07-12T16:49:00Z",
      "timezone": "(GMT+00:00) Europe/London",
      "utc_offset": 3600.0,
      "location_city": null,
      "location_state": null,
      "location_country": "United Kingdom",
      "achievement_count": 0,
      "kudos_count": 2,
      "comment_count": 0,
      "athlete_count": 1,
      "photo_count": 0,
      "map": {
        "id": "a9438118261",
        "summary_polyline": "",
        "resource_state": 2
      },
      "trainer": false,
      "commute": false,
      "manual": true,
      "private": false,
      "visibility": "everyone",
      "flagged": false,
      "gear_id": null,
      "start_latlng": [],
      "end_latlng": [],
      "average_speed": 0.533,
      "max_speed": 0,
      "has_heartrate": false,
      "heartrate_opt_out": false,
      "display_hide_heartrate_option": false,
      "upload_id": null,
      "external_id": null,
      "from_accepted_tag": false,
      "pr_count": 0,
      "total_photo_count": 0,
      "has_kudoed": false
    },
    {
      "resource_state": 2,
      "athlete": {
        "id": 14952541,
        "resource_state": 1
      },
      "name": "Afternoon Ride",
      "distance": 36693.0,
      "moving_time": 5400,
      "elapsed_time": 5400,
      "total_elevation_gain": 0,
      "type": "VirtualRide",
      "sport_type": "VirtualRide",
      "id": 9431452531,
      "start_date": "2023-07-11T14:24:31Z",
      "start_date_local": "2023-07-11T15:24:31Z",
      "timezone": "(GMT+00:00) Europe/London",
      "utc_offset": 3600.0,
      "location_city": null,
      "location_state": null,
      "location_country": "United Kingdom",
      "achievement_count": 0,
      "kudos_count": 3,
      "comment_count": 0,
      "athlete_count": 1,
      "photo_count": 0,
      "map": {
        "id": "a9431452531",
        "summary_polyline": "",
        "resource_state": 2
      },
      "trainer": false,
      "commute": false,
      "manual": true,
      "private": false,
      "visibility": "everyone",
      "flagged": false,
      "gear_id": null,
      "start_latlng": [],
      "end_latlng": [],
      "average_speed": 6.795,
      "max_speed": 0,
      "has_heartrate": false,
      "heartrate_opt_out": false,
      "display_hide_heartrate_option": false,
      "upload_id": null,
      "external_id": null,
      "from_accepted_tag": false,
      "pr_count": 0,
      "total_photo_count": 0,
      "has_kudoed": false
    },
    {
      "resource_state": 2,
      "athlete": {
        "id": 14952541,
        "resource_state": 1
      },
      "name": "Evening Run",
      "distance": 5015.8,
      "moving_time": 1318,
      "elapsed_time": 1364,
      "total_elevation_gain": 36.0,
      "type": "Run",
      "sport_type": "Run",
      "workout_type": 0,
      "id": 9425445417,
      "start_date": "2023-07-10T16:50:41Z",
      "start_date_local": "2023-07-10T17:50:41Z",
      "timezone": "(GMT+00:00) Europe/London",
      "utc_offset": 3600.0,
      "location_city": null,
      "location_state": null,
      "location_country": "United Kingdom",
      "achievement_count": 1,
      "kudos_count": 2,
      "comment_count": 0,
      "athlete_count": 1,
      "photo_count": 0,
      "map": {
        "id": "a9425445417",
        "summary_polyline": "qhryHvnh@F[NUD_@Vs@D]DC@IBaACWF[AI@KFSFOD]\\m@L?NY?YLM@]FM?]BEBSJg@\\c@BIPSR]FUJGBGHCLNJ^b@j@DRNXBL`@l@Zx@PTBFHJPLHRDDLFNGHIBHFBH?BJLZDBFARWHGJYd@]BKLIT[?GTSHOl@q@Pc@DCLABG\\ULCNYh@c@BG\\Mh@o@HORILMh@Up@q@N?DCDKTSl@_@Vc@x@i@VUH@HOD?RMLYDDRORGVe@XMFBDET]RCHQLIBGZUDKTU`@YPIZ[JBHC\\WBGVKFXFATSFABIDEZGL?FQDCJ?PLJjAGDHJFTJl@@\\DN@`@PfA@XBD?HGXHVFjAL\\HLANNbAJvADFD\\FPA^FZ@p@Hd@FdAP~@Bl@Rv@BrAJZLdAFTDx@Hf@?VHNCJPv@Bl@HZBFF`@APBNNx@DDAJFD@b@H^LxAL~@?HLz@?TJp@?HDFAHFl@Z|@Bb@DTAHJh@@VDNDj@H^?NKLCCEBO@GDEJWJU`@OFIJGBCCG?EFQJUTI@EAEDIAKBAFSNU\\QFKAEBQVSJEH?DIDEAEGABALGFU?MDCRILM@OLKKCLKFCPINIBGEEBQ?MFCDECMLGJE@GPCRG?Ol@IHKBOVE@KFOBKNI?GNG@ILOFWX[PKLWLEFM?IR]XC?YVQZOHIRQBGXi@XCFIDAPCFKBMXc@l@G@SPAH}@`AWJEFGPWRQZYTS\\KJIRc@b@[b@EBc@b@GNWPE@EFKJIJKDEHG?[VS^GBILUJWJGFI@y@p@oAb@QAG@ECIFOKm@?UI[COK_@MKGIMGAIGMe@M{@c@oA@MFGAKUM]i@Eg@MSOa@Qu@Qa@Ik@Ai@MQIAGISo@_@c@}@i@[MOCM@IQG@ICYSWAQCIGKBQGOAo@UGKcAIOEEBWUMG}@EKMMAEKCm@Ha@A]BSCSBIHKASCM@YF_@?m@FGFe@ByAF_APcA?U",
        "resource_state": 2
      },
      "trainer": false,
      "commute": false,
      "manual": false,
      "private": false,
      "visibility": "everyone",
      "flagged": false,
      "gear_id": "g13518149",
      "start_latlng": [
        51.54533229768276,
        -0.21429852582514286
      ],
      "end_latlng": [
        51.54548845253885,
        -0.21483027376234531
      ],
      "average_speed": 3.806,
      "max_speed": 5.822,
      "has_heartrate": false,
      "heartrate_opt_out": false,
      "display_hide_heartrate_option": false,
      "elev_high": 62.0,
      "elev_low": 33.6,
      "upload_id": 10109342357,
      "upload_id_str": "10109342357",
      "external_id": "98D68E98-D78D-4512-9740-E2EAD256E850-activity.fit",
      "from_accepted_tag": false,
      "pr_count": 0,
      "total_photo_count": 0,
      "has_kudoed": false
    },
    {
      "resource_state": 2,
      "athlete": {
        "id": 14952541,
        "resource_state": 1
      },
      "name": "Morning Run",
      "distance": 5127.3,
      "moving_time": 1335,
      "elapsed_time": 1336,
      "total_elevation_gain": 36.2,
      "type": "Run",
      "sport_type": "Run",
      "workout_type": 0,
      "id": 9404068390,
      "start_date": "2023-07-07T07:25:42Z",
      "start_date_local": "2023-07-07T08:25:42Z",
      "timezone": "(GMT+00:00) Europe/London",
      "utc_offset": 3600.0,
      "location_city": null,
      "location_state": null,
      "location_country": "United Kingdom",
      "achievement_count": 1,
      "kudos_count": 1,
      "comment_count": 0,
      "athlete_count": 1,
      "photo_count": 0,
      "map": {
        "id": "a9404068390",
        "summary_polyline": "yiryHbrh@DMHG`@sB@SP]Jq@Rk@FeA?]BEFg@DI@YDSDMXc@DSLWHIBGDu@Rs@@MPi@p@cALYX[F@VVDPP^?HHDd@x@RRp@bAP`@LFFPFBHLJQHEHR?JFJHDFTHDFFFBD?R[F?Pc@VITg@RMHAHWDAFSJIBK^UDGDDJOLQJ]JALMHKJEDED@Lk@XCLMD@HARHP_@N?LWD?LMLCPMDGh@g@D?DWFCNABEPMXKBIDCFDHSVQFALMBGRMJOPKRWDCFALUJK@IH@HMHDHCDEDODCBIRIVABOh@UN@V]P]NATSNGJ_@P?NMHOTKTSFADIDDVUF?PUJBFAFGLC\\OTELHDH?VLr@@j@TfAHr@Dh@@\\CJ?HJh@ARHv@APBZF\\LbBJz@VbADp@FFCLBHDp@FTLpAFVJVD`@ALNn@EJAHDN?d@RlAFt@FNAJJx@DXBF?XBLPt@Hz@Nn@JtAFj@H\\Dp@LfAVdABp@Hp@VtABDHp@HV@^Nf@Bz@Hf@CPF\\MLIBQRE?UTQHGHMDKLGBKLUJO?IAIHCLMDKRe@TEHEDG?GLUDGAINM?EBCHGBEDIAORe@^EREDYHQ?IEK?EFSLUr@GBKRG?CDGPWJKT[Zi@b@MBSNc@TCF_@NGLG?IDMX[RY\\WRMFEFi@XCDCPOLINCH]^CJKJOFIXOTUVE@EHIDYVOHERY\\MD_@h@i@f@ORKViAfA_@j@QLORG@g@l@E@EFwBtBWH_@d@UFCF_@P[?OLc@Ja@Gg@ASKW?UIk@AQMCSCDIKECKQEi@?MCOKQMg@MY?[MWCCMECGKa@O]GYMYG]KOQy@KOC[D]AGCEK?KEQi@Ua@i@e@q@[o@WG?MEKIOGg@KIGWAKIc@IM@KKEOICQFCBOIa@Mg@Gw@UQCKMGQ@m@AKDe@Ao@Dq@AMBe@AMPu@@w@Di@De@Je@@e@NoA",
        "resource_state": 2
      },
      "trainer": false,
      "commute": false,
      "manual": false,
      "private": false,
      "visibility": "everyone",
      "flagged": false,
      "gear_id": "g13666902",
      "start_latlng": [
        51.54551745392382,
        -0.2148770447820425
      ],
      "end_latlng": [
        51.54534252360463,
        -0.2144098374992609
      ],
      "average_speed": 3.841,
      "max_speed": 5.768,
      "has_heartrate": false,
      "heartrate_opt_out": false,
      "display_hide_heartrate_option": false,
      "elev_high": 62.0,
      "elev_low": 33.6,
      "upload_id": 10086656054,
      "upload_id_str": "10086656054",
      "external_id": "3BB5CE83-E3DC-4E11-B05D-A5EF1B23B5A0-activity.fit",
      "from_accepted_tag": false,
      "pr_count": 0,
      "total_photo_count": 0,
      "has_kudoed": false
    },
    {
      "resource_state": 2,
      "athlete": {
        "id": 14952541,
        "resource_state": 1
      },
      "name": "Afternoon Ride",
      "distance": 21726.2,
      "moving_time": 3600,
      "elapsed_time": 3600,
      "total_elevation_gain": 0,
      "type": "VirtualRide",
      "sport_type": "VirtualRide",
      "id": 9393623927,
      "start_date": "2023-07-05T14:22:03Z",
      "start_date_local": "2023-07-05T15:22:03Z",
      "timezone": "(GMT+00:00) Europe/London",
      "utc_offset": 3600.0,
      "location_city": null,
      "location_state": null,
      "location_country": "United Kingdom",
      "achievement_count": 0,
      "kudos_count": 1,
      "comment_count": 0,
      "athlete_count": 1,
      "photo_count": 0,
      "map": {
        "id": "a9393623927",
        "summary_polyline": "",
        "resource_state": 2
      },
      "trainer": false,
      "commute": false,
      "manual": true,
      "private": false,
      "visibility": "everyone",
      "flagged": false,
      "gear_id": null,
      "start_latlng": [],
      "end_latlng": [],
      "average_speed": 6.035,
      "max_speed": 0,
      "has_heartrate": false,
      "heartrate_opt_out": false,
      "display_hide_heartrate_option": false,
      "upload_id": null,
      "external_id": null,
      "from_accepted_tag": false,
      "pr_count": 0,
      "total_photo_count": 0,
      "has_kudoed": false
    },
    {
      "resource_state": 2,
      "athlete": {
        "id": 14952541,
        "resource_state": 1
      },
      "name": "Afternoon Run",
      "distance": 3096.0,
      "moving_time": 1031,
      "elapsed_time": 1055,
      "total_elevation_gain": 3.5,
      "type": "Run",
      "sport_type": "Run",
      "workout_type": 0,
      "id": 9387711551,
      "start_date": "2023-07-04T16:11:01Z",
      "start_date_local": "2023-07-04T17:11:01Z",
      "timezone": "(GMT+00:00) Europe/London",
      "utc_offset": 3600.0,
      "location_city": null,
      "location_state": null,
      "location_country": "United Kingdom",
      "achievement_count": 1,
      "kudos_count": 2,
      "comment_count": 0,
      "athlete_count": 1,
      "photo_count": 0,
      "map": {
        "id": "a9387711551",
        "summary_polyline": "s_ryHxrh@JYJO@IJMDUHEHWJG@IJODOd@w@L\\FICYBGRNBHXh@PPDPNJ@FJHDJHBVZFJHCF@^VLNv@lADPTT@NTPR^NNDHD@PZTVH@Rl@JHDHFBPXFDNXr@dABFHDFNDBFAHBDRAJGHCL@B@@?EFFCT[j@IXMPALbAjBLLHTHHDJJ@Xo@BAd@u@hAyBPQBICKPODI?ICGIGIKQ[IGCI]i@o@w@EKECBKE@?AC@?CB?@E?IHS@IIc@R_@}@w@Q_@MIGOGEOUGAS_@EAIIEQIGUe@MEOOKSOKCOECM[KEK]IECI]g@QOKUOMCKQSIQS[MKCIFG@IAWECE@GGKWWSGSEGL]FOJGb@o@LIFOHEFWNEDI\\WHIFMNOJQJHHXRP@J\\d@DT`@ZZ@JCDNVT@FHFDLF@V^TRHPNNF@LXD?DHHBVLXEH?@GH?XLJ?LKRELIPENMPKPQp@g@LURIb@[RATGF@VITBDCRJJHRBFLVPHAPTFBFPRXJ`@FJZTL?VZH?VJNBNEh@CPKDMJI`@WVY^{@Hg@FOHkAMyAMu@DOP?FIDI?I?QCEWcB",
        "resource_state": 2
      },
      "trainer": false,
      "commute": false,
      "manual": false,
      "private": false,
      "visibility": "everyone",
      "flagged": false,
      "gear_id": "g13518149",
      "start_latlng": [
        51.544802812859416,
        -0.21347458474338055
      ],
      "end_latlng": [
        51.53464889153838,
        -0.2049922663718462
      ],
      "average_speed": 3.003,
      "max_speed": 7.404,
      "has_heartrate": false,
      "heartrate_opt_out": false,
      "display_hide_heartrate_option": false,
      "elev_high": 62.5,
      "elev_low": 34.9,
      "upload_id": 10069450606,
      "upload_id_str": "10069450606",
      "external_id": "0F8843C8-D157-4EC2-A3E0-693BB50C6366-activity.fit",
      "from_accepted_tag": false,
      "pr_count": 0,
      "total_photo_count": 0,
      "has_kudoed": false
    },
    {
      "resource_state": 2,
      "athlete": {
        "id": 14952541,
        "resource_state": 1
      },
      "name": "Afternoon Swim",
      "distance": 800.0,
      "moving_time": 1500,
      "elapsed_time": 1500,
      "total_elevation_gain": 0,
      "type": "Swim",
      "sport_type": "Swim",
      "id": 9387184757,
      "start_date": "2023-07-04T14:50:25Z",
      "start_date_local": "2023-07-04T15:50:25Z",
      "timezone": "(GMT+00:00) Europe/London",
      "utc_offset": 3600.0,
      "location_city": null,
      "location_state": null,
      "location_country": "United Kingdom",
      "achievement_count": 0,
      "kudos_count": 0,
      "comment_count": 0,
      "athlete_count": 1,
      "photo_count": 0,
      "map": {
        "id": "a9387184757",
        "summary_polyline": "",
        "resource_state": 2
      },
      "trainer": false,
      "commute": false,
      "manual": true,
      "private": false,
      "visibility": "everyone",
      "flagged": false,
      "gear_id": null,
      "start_latlng": [],
      "end_latlng": [],
      "average_speed": 0.533,
      "max_speed": 0,
      "has_heartrate": false,
      "heartrate_opt_out": false,
      "display_hide_heartrate_option": false,
      "upload_id": null,
      "external_id": null,
      "from_accepted_tag": false,
      "pr_count": 0,
      "total_photo_count": 0,
      "has_kudoed": false
    },
    {
      "resource_state": 2,
      "athlete": {
        "id": 14952541,
        "resource_state": 1
      },
      "name": "Afternoon Ride",
      "distance": 43798.9,
      "moving_time": 5413,
      "elapsed_time": 5413,
      "total_elevation_gain": 0,
      "type": "VirtualRide",
      "sport_type": "VirtualRide",
      "id": 9381396693,
      "start_date": "2023-07-03T15:17:07Z",
      "start_date_local": "2023-07-03T16:17:07Z",
      "timezone": "(GMT+00:00) Europe/London",
      "utc_offset": 3600.0,
      "location_city": null,
      "location_state": null,
      "location_country": "United Kingdom",
      "achievement_count": 0,
      "kudos_count": 0,
      "comment_count": 0,
      "athlete_count": 1,
      "photo_count": 0,
      "map": {
        "id": "a9381396693",
        "summary_polyline": "",
        "resource_state": 2
      },
      "trainer": false,
      "commute": false,
      "manual": true,
      "private": false,
      "visibility": "everyone",
      "flagged": false,
      "gear_id": null,
      "start_latlng": [],
      "end_latlng": [],
      "average_speed": 8.091,
      "max_speed": 0,
      "has_heartrate": false,
      "heartrate_opt_out": false,
      "display_hide_heartrate_option": false,
      "upload_id": null,
      "external_id": null,
      "from_accepted_tag": false,
      "pr_count": 0,
      "total_photo_count": 0,
      "has_kudoed": false
    },
    {
      "resource_state": 2,
      "athlete": {
        "id": 14952541,
        "resource_state": 1
      },
      "name": "Evening Run",
      "distance": 5104.4,
      "moving_time": 1466,
      "elapsed_time": 1466,
      "total_elevation_gain": 36.6,
      "type": "Run",
      "sport_type": "Run",
      "workout_type": 0,
      "id": 9376210271,
      "start_date": "2023-07-02T16:53:54Z",
      "start_date_local": "2023-07-02T17:53:54Z",
      "timezone": "(GMT+00:00) Europe/London",
      "utc_offset": 3600.0,
      "location_city": null,
      "location_state": null,
      "location_country": "United Kingdom",
      "achievement_count": 0,
      "kudos_count": 2,
      "comment_count": 0,
      "athlete_count": 1,
      "photo_count": 0,
      "map": {
        "id": "a9376210271",
        "summary_polyline": "ohryHzmh@LW\\iADi@DEBOFaBB]Nk@`@_AJGLk@HCDIJy@LkABEDOTc@VYJUZc@HCNHJZ^d@@HJRTh@RRVl@RRXj@BLHLBDNBJCN@ZXPZPNHEJWV[F?NMV]F@`@s@Za@`@]^o@d@[HONIHKF?DGJGX_@NEJQd@[HAFMPIJQD?NMTW^SBGXM\\[LGj@u@DIXILIFKHCXc@DADGLGFKPMBEXOLKB?f@i@NAv@a@HKB?DGJA\\o@^MPSNENKBIDGHEDGHEH@FCJKDAHMVMD?HNB@`@[FABIFCD@JEFBJKL@FEJAFHFrAFX@XH\\@TF`@NdBHTCv@Dx@DXAHDZNVD^Bb@DPNdBHj@BF?`@Hb@?`@FZRrBHb@Dr@FT?\\FNFF@HCRVjA?TPbADnAH`@D`@@^HRB^LZHl@B\\CJPjABJHB@NDL@~@LdAL`ABF?HPh@?THp@Jf@BT?HJd@Jr@@f@D\\Lr@JP?`@CDWLKJQ@ONWJi@^GB[VEAIBQLG@EFs@p@QHCHI@KJKBMASPABICEJMHIJGAIN[Z]LIHODOLGNKHCFE?GDKP[^IPI@CDE@UNGHE@IJg@`@OBCD_@PORc@VKNMD[VCFIDMRWRSROJCDOJ[b@KBKVGHKDGNIFg@v@[ZUZy@p@GN]^EBOPGLe@f@UZIFOP_@l@E@KHg@n@QLAHQLKPQDYb@IDCFUPMT_Ap@IL[RYJUTK?WNK@GCI?MDEFe@J[CEBE?K?SKUAKBWGEEO?KEM?e@_@IUAg@IYG?SaA?KGQAa@QSICEGCQKYIKUk@IKI}@_@oA?SDMIMQGCEQi@EAGM]e@i@_@MASSQA_@KKGMOGAEEq@EGEUCGEE@QGYQKCG@CKIEG?IFKBSGE@EG_@Oc@KW?GJOAGOGAKOGc@Ba@BKAU?SEMBQFM?MFm@?o@Dm@FSCIBGLkBN_AFgADODe@DGDs@Ni@@WJy@",
        "resource_state": 2
      },
      "trainer": false,
      "commute": false,
      "manual": false,
      "private": false,
      "visibility": "everyone",
      "flagged": false,
      "gear_id": "g13518149",
      "start_latlng": [
        51.545275300741196,
        -0.21420858800411224
      ],
      "end_latlng": [
        51.54512744396925,
        -0.21383089944720268
      ],
      "average_speed": 3.482,
      "max_speed": 5.238,
      "has_heartrate": false,
      "heartrate_opt_out": false,
      "display_hide_heartrate_option": false,
      "elev_high": 62.0,
      "elev_low": 33.6,
      "upload_id": 10057321047,
      "upload_id_str": "10057321047",
      "external_id": "DEB77CB4-A222-448B-AD0A-A9D068A9FB5C-activity.fit",
      "from_accepted_tag": false,
      "pr_count": 0,
      "total_photo_count": 0,
      "has_kudoed": false
    },
    {
      "resource_state": 2,
      "athlete": {
        "id": 14952541,
        "resource_state": 1
      },
      "name": "Morning Ride",
      "distance": 23013.7,
      "moving_time": 3600,
      "elapsed_time": 3600,
      "total_elevation_gain": 0,
      "type": "VirtualRide",
      "sport_type": "VirtualRide",
      "id": 9366268126,
      "start_date": "2023-07-01T07:08:31Z",
      "start_date_local": "2023-07-01T08:08:31Z",
      "timezone": "(GMT+00:00) Europe/London",
      "utc_offset": 3600.0,
      "location_city": null,
      "location_state": null,
      "location_country": "United Kingdom",
      "achievement_count": 0,
      "kudos_count": 0,
      "comment_count": 0,
      "athlete_count": 1,
      "photo_count": 0,
      "map": {
        "id": "a9366268126",
        "summary_polyline": "",
        "resource_state": 2
      },
      "trainer": false,
      "commute": false,
      "manual": true,
      "private": false,
      "visibility": "everyone",
      "flagged": false,
      "gear_id": null,
      "start_latlng": [],
      "end_latlng": [],
      "average_speed": 6.393,
      "max_speed": 0,
      "has_heartrate": false,
      "heartrate_opt_out": false,
      "display_hide_heartrate_option": false,
      "upload_id": null,
      "external_id": null,
      "from_accepted_tag": false,
      "pr_count": 0,
      "total_photo_count": 0,
      "has_kudoed": false
    }
  ]);
}
